// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mbsdteafiguyywjrrhax.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ic2R0ZWFmaWd1eXl3anJyaGF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3NjUwNTAsImV4cCI6MjA2MzM0MTA1MH0.M7KppdRjNuspWmbQ0YVaK4H6-q3c7v5FWvPh2VTuvzI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);